#!/usr/bin/env python3
# Convert single-row font sprite sheet PNG to C array for 3DS embedding

import sys
import os
from PIL import Image
import string

def single_row_font_sheet_to_c(png_file, output_file, array_name, glyph_size=24):
    """Convert single-row font sprite sheet to C arrays"""
    
    try:
        # Load the sprite sheet
        img = Image.open(png_file)
        
        # Convert to RGB if needed
        if img.mode != 'RGB':
            img = img.convert('RGB')
        
        width, height = img.size
        
        print(f"🎨 Converting single-row font sheet to C arrays")
        print(f"📄 Input: {png_file}")
        print(f"📏 Size: {width}x{height} pixels")
        print(f"🔤 Glyph size: {glyph_size}x{glyph_size}")
        print(f"📊 Layout: Single row, {width//glyph_size} characters")
        
        # Characters in order (same as TTF converter)
        chars = (
            string.ascii_uppercase +  # A-Z
            string.ascii_lowercase +  # a-z
            string.digits +           # 0-9
            " !?.,-+/=_@#$%^&()[]{}<>:;"  # Symbols
        )
        
        # Verify the image has the right dimensions
        expected_width = len(chars) * glyph_size
        if height != glyph_size:
            print(f"⚠️  Warning: Height is {height}, expected {glyph_size}")
        if width != expected_width:
            print(f"⚠️  Warning: Width is {width}, expected {expected_width} for {len(chars)} characters")
        
        # Create header file
        with open(output_file, 'w') as f:
            f.write(f"// Pokemon Font Sprite Sheet (Single Row) - Generated by single_row_font_sheet_to_c.py\n")
            f.write(f"#ifndef _{array_name.upper()}_H_\n")
            f.write(f"#define _{array_name.upper()}_H_\n\n")
            f.write(f"#include <stddef.h>\n\n")
            
            f.write(f"// Font sprite sheet data\n")
            f.write(f"extern const unsigned char {array_name}_bgr[];\n")
            f.write(f"extern const unsigned int {array_name}_bgr_size;\n\n")
            
            f.write(f"// Font properties (SINGLE ROW LAYOUT)\n")
            f.write(f"#define {array_name.upper()}_GLYPH_WIDTH {glyph_size}\n")
            f.write(f"#define {array_name.upper()}_GLYPH_HEIGHT {glyph_size}\n")
            f.write(f"#define {array_name.upper()}_COLUMNS {len(chars)}  // Single row = all characters in columns\n")
            f.write(f"#define {array_name.upper()}_ROWS 1  // Single row layout\n\n")
            
            f.write(f"// Character to index mapping\n")
            f.write(f"int {array_name}_get_char_index(char c);\n\n")
            
            f.write(f"// Character order reference\n")
            f.write(f"// {chars}\n\n")
            
            f.write(f"#endif // _{array_name.upper()}_H_\n")
        
        # Create source file
        source_file = output_file.replace('.h', '.c')
        with open(source_file, 'w') as f:
            f.write(f"// Pokemon Font Sprite Sheet (Single Row) - Generated by single_row_font_sheet_to_c.py\n")
            f.write(f"#include \"{os.path.basename(output_file)}\"\n\n")
            
            # Convert entire sprite sheet to BGR
            pixels = []
            for y in range(height):
                for x in range(width):
                    r, g, b = img.getpixel((x, y))
                    # Convert to BGR format for 3DS
                    pixels.extend([b, g, r])
            
            # Write sprite sheet data
            f.write(f"// Font sprite sheet BGR data (single row)\n")
            f.write(f"const unsigned char {array_name}_bgr[] = {{\n")
            
            for i, pixel in enumerate(pixels):
                if i % 16 == 0:
                    f.write("    ")
                f.write(f"0x{pixel:02X}")
                if i < len(pixels) - 1:
                    f.write(", ")
                if i % 16 == 15:
                    f.write("\n")
            
            if len(pixels) % 16 != 0:
                f.write("\n")
            
            f.write(f"}};\n\n")
            f.write(f"const unsigned int {array_name}_bgr_size = {len(pixels)};\n\n")
            
            # Write character mapping function
            f.write(f"// Get character index in sprite sheet (single row layout)\n")
            f.write(f"int {array_name}_get_char_index(char c) {{\n")
            f.write(f"    switch (c) {{\n")
            
            for i, char in enumerate(chars):
                if char == '"':
                    f.write(f"        case '\"': return {i};\n")
                elif char == '\\':
                    f.write(f"        case '\\\\': return {i};\n")
                elif char == '\'':
                    f.write(f"        case '\\'': return {i};\n")
                elif char == '\n':
                    f.write(f"        case '\\n': return {i};\n")
                elif char == '\r':
                    f.write(f"        case '\\r': return {i};\n")
                elif char == '\t':
                    f.write(f"        case '\\t': return {i};\n")
                else:
                    f.write(f"        case '{char}': return {i};\n")
            
            f.write(f"        default: return {chars.index(' ')}; // Space as fallback\n")
            f.write(f"    }}\n")
            f.write(f"}}\n")
        
        print(f"✅ Converted single-row font sheet to {output_file} and {source_file}")
        print(f"📏 Total pixels: {len(pixels)}")
        print(f"🔤 Characters mapped: {len(chars)}")
        print(f"🎯 Layout: Single row prevents character bleeding!")
        return True
        
    except Exception as e:
        print(f"❌ Error converting font sheet: {e}")
        return False

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python single_row_font_sheet_to_c.py <font_sheet.png> <output.h> <array_name>")
        print("Example: python single_row_font_sheet_to_c.py pokemon_font_single_row.png pokemon_font_sheet.h pokemon_font")
        print("")
        print("This converts a single-row PNG font sheet to C arrays.")
        print("The single-row layout prevents character bleeding issues.")
        sys.exit(1)
    
    png_file = sys.argv[1]
    output_file = sys.argv[2]
    array_name = sys.argv[3]
    
    if not os.path.exists(png_file):
        print(f"❌ Font sheet not found: {png_file}")
        sys.exit(1)
    
    success = single_row_font_sheet_to_c(png_file, output_file, array_name)
    sys.exit(0 if success else 1)
